### ISSUE TITLE
Dashboard, navigation

### ISSUE THREAD

**Issue by bkkEvan** [wootwoot1234/Superhost-Tools#47] opened 2018-03-30 06:39 UTC
You tried to simplify the dashboard last week by not showing the whole thing and cutting it to 10 messages per pag, which seem like amazing idea and made it look accurate and less cluttered,
but actually that made it difficult to use: as before i used F3 on my keyboard to look for the guest name, and now i need to press next page and read each page to find it and sometimes it is on the 5th+ page
if you can return the old system back it will be handy even it looks not that nice like a new one

**Comment by bkkEvan** [comment] 2018-03-30 12:28
there is also one bug with dashboard which doesn't
![capture](https://user-images.githubusercontent.com/36990735/38137708-74269368-3450-11e8-85ac-4a2ff4cc4a7b.JPG)
 affects anything but maybe you want to know

**Comment by bkkEvan** [comment] 2018-03-30 12:28
![capture](https://user-images.githubusercontent.com/36990735/38137730-95664e92-3450-11e8-8fd1-067cd5b9fadf.JPG)

**Comment by wootwoot1234** [comment] 2018-03-30 17:00
Thanks for this bug, I'll take a look.  I'll also look into adding a search feature.

**Comment by wootwoot1234** [comment] 2018-03-30 23:44
I submitted a fix to the code but it's hard to test because my account isn't having the issues.  Can you check your dashboard now?  Is that bug fixed?

Thanks,
Tom

**Comment by bkkEvan** [comment] 2018-03-30 23:47
I will answer your morning time ;) 6:44 AM, March 31, 2018, Tom <notifications@github.com>:I submitted a fix to the code but it's hard to test because my account isn't having the issues.  Can you check your dashboard now?  Is that bug fixed?
Thanks,
Tom

**Comment by bkkEvan** [comment] 2018-03-31 01:38
seem fixed, thx

**Comment by bkkEvan** [comment] 2018-03-31 23:07
yesterday i deleted the second profile i created and connected listings to this profile
but i am a co-host for the other profile as well, so superhosttools didnt take the same listing from the primary host and co-host well, its being crazy for about 1 hour but then i renamed the same listings and this morning everything seems to be in order

Is there a way to remove some particular listings from your profile?

**Comment by wootwoot1234** [comment] 2018-03-31 23:51
I’m still confused, what happened?

**Comment by bkkEvan** [comment] 2018-04-01 01:47
i added one more profile which included the same listings (as i am co-host at my first profile)
once i did that superhosttools start copying messages to dashboard unlimited amount of times and when your click listings the list expanded unlimited down

i disconnected second profile, renamed the duplicating listings and connected again - it seem to solve the problem

**Comment by bkkEvan** [comment] 2018-04-01 16:13
@wootwoot1234 Can you return the old dashboard? i am struggling with searches.

**Comment by wootwoot1234** [comment] 2018-04-02 01:04
You can now hide listings if you go to the listing's settings.  I'm also working on adding a search feature to the dashboard.

**Comment by bkkEvan** [comment] 2018-04-02 01:05
Thank you, you are a treasure 8:04 AM, April 2, 2018, Tom <notifications@github.com>:You can now hide listings if you go to the listing's settings.  I'm also working on adding a search feature to the dashboard.

**Comment by wootwoot1234** [comment] 2018-04-02 01:13
Can you move it to now?

**Comment by bkkEvan** [comment] 2018-04-02 01:18
Gimme an hour or so. Still walking dogs8:13 AM, April 2, 2018, Tom <notifications@github.com>:Can you move it to now?

**Comment by wootwoot1234** [comment] 2018-04-02 01:19
ok, let me know when you set it to go.

**Comment by bkkEvan** [comment] 2018-04-02 02:39
and about dashboard it start showing messages from march 31st and some of messages are still doubled, also non-sent messages are not doing the red color anymore

**Comment by bkkEvan** [comment] 2018-04-02 02:40
![capture](https://user-images.githubusercontent.com/36990735/38180895-e20882c8-3659-11e8-9f02-1e1d58d4b5de.JPG)
this shows when i click dashboard

**Comment by bkkEvan** [comment] 2018-04-02 02:42
some messages are showing two times
![capture](https://user-images.githubusercontent.com/36990735/38180915-11a1e3da-365a-11e8-9431-eb1f3d1c2d1d.JPG)
and ones were not sent are white

**Comment by bkkEvan** [comment] 2018-04-02 02:44
@wootwoot1234 sorry to bother you a lot

**Comment by wootwoot1234** [comment] 2018-04-02 02:47
Thanks for pointing out that issue.  I think I have a fix for it but I need to make sure I don't lose the logs for review.  Have you set it to go out yet?  If not, I can submit the fix.  If you're already set it to go out I'll submit the fix after I've downloaded the logs.  Have you set the review from the new account to go out?

**Comment by bkkEvan** [comment] 2018-04-02 02:48
2 for 10 am and 1 for 11 am

**Comment by wootwoot1234** [comment] 2018-04-02 02:49
Ok, thanks.  I'll submit the fix now then.

**Comment by wootwoot1234** [comment] 2018-04-02 03:13
I downloaded the logs and I see where the issue is I'm just not sure why it's happening.  I'll look into it more tomorrow but I'm too tired to figure it out right now.  :)  BTW, I have a search feature almost ready to go, should be ready tomorrow.

**Comment by bkkEvan** [comment] 2018-04-02 05:26
great news about search feature, about reviews at 12 pm there was 41 error messages from superhosttools
![capture](https://user-images.githubusercontent.com/36990735/38184334-1cd53114-3671-11e8-9cae-ee81c41efbbc.JPG)

**Comment by wootwoot1234** [comment] 2018-04-02 14:16
Let's keep the review bug conversation here: https://github.com/wootwoot1234/Superhost-Tools/issues/43

I'll submit the new search feature in an hour or two.

**Comment by wootwoot1234** [comment] 2018-04-02 14:38
The search feature is live.  You'll need to clear the cache in your browser to see it (or just restart your browser).  Let me know how it works for you.

**Comment by wootwoot1234** [comment] 2018-04-02 15:49
I just submitted another update to the search feature that fixes a few bugs so clear your cache again if you already started testing it.

**Comment by bkkEvan** [comment] 2018-04-02 23:04
haleloo, search works. 
Now there is a new thing

I want to disable all future reviews for the Guest named Somchai
I put Somchai in the search - scheduled reviews appear on dashboard
i select the drop down in the top right corner press actions and select Disable
nothing happens message does not get disabled

**Comment by bkkEvan** [comment] 2018-04-03 00:46
@wootwoot1234 did you see about disabling review?

**Comment by wootwoot1234** [comment] 2018-04-03 00:53
Yes but I had forgotten...  Can you do me a favor and when you find a new bug start a new "issue" so that I can keep track of them?  I get a little lost on these long threads and I use the open "issues" as a kind of todo list.  :)  I'm going to close this issue since the search seems to be working.

**Closed by wootwoot1234** 2018-04-03 00:53 UTC
Labels: bug, enhancement
