### ISSUE TITLE
sign in and Airbnb linkage.

### ISSUE THREAD

**Issue by josephcooksfarm** [wootwoot1234/Superhost-Tools#9] opened 2017-08-22 21:12 UTC
I'm having the sign-in problem again.  First, I received a message that the AirBnB password didn't work.  But it had worked a couple of days ago.
Now, the program isn't accepting my login password, either from memory or from my manual entry.

**Comment by wootwoot1234** [comment] 2017-08-23 18:46
Thanks for reporting this bug. I'm trying to figure out the cause. Some users account seem to need verification often and others (like mine) are only asked once. Are you using another service like superhosttools that you shared your Airbnb login credentials with?  I wonder if it has to do with too many calls to your account? If you are using another service, are you being required to login again there too?

**Comment by josephcooksfarm** [comment] 2017-08-24 10:53
Hi Tom,

No I'm not using any other service besides Superhost Tools. Thanks.

**Comment by wootwoot1234** [comment] 2017-08-26 16:30
I just added some code that hopefully will fix this issue.  I just wrote about it here.  I think these two issues are related:

https://github.com/wootwoot1234/Superhost-Tools/issues/5

**Comment by wootwoot1234** [comment] 2017-08-26 16:30
Please let me know if this happens to you again.

**Comment by wootwoot1234** [comment] 2017-09-05 19:41
I'm going to close this issue because I think the issue is fixed. Please let me know if it happens again.

**Closed by wootwoot1234** 2017-09-05 19:41 UTC

**Comment by josephcooksfarm** [comment] 2017-09-05 23:39
Will do, thanks.
